### ISSUE TITLE
Doesn't work when components are internationalized using react-intl

### ISSUE THREAD

**Issue by scazzy** [planttheidea/react-rendered-size#4]
Whenever getRenderedSize is used to render the component and calculate it's size, it throws error that Intl context is required. 
```
Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```

**Comment by planttheidea** [comment]
This is because you are using React Context, and such a provider needs to exist in the tree for rendering to work. If you wrap your component in such a provider with the same context values, it should work as expected.

```js
const size = getRenderedSize(
  <IntlProvider locale={usersLocale} messages={translationsForUsersLocale}>
    <MyInternationalizedComponent />
  </IntlProvider>
);
```

This will establish an entirely new React tree, which means any components relying on any context will need to have that context re-established.
